name: flutter_template
description: A template project for Flutter applications
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  api_repository:
    path: libs/api_repository
  app_ui:
    path: libs/app_ui
  bloc: ^8.1.4
  database_client:
    path: libs/database_client
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: libs/form_fields
  formz: ^0.8.0
  go_router: ^15.1.2
  intl: ^0.19.0
  powersync_repository:
    path: libs/powersync_repository
  shared:
    path: libs/shared
  supabase_auth_client:
    path: libs/auth_client/supabase_auth_client
  supabase_flutter: ^2.8.4
  user_repository:
    path: libs/user_repository


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
