name: flutter_template
description: A template project for Flutter applications
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  api_repository:
    path: libs/api_repository
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  powersync_repository:
    path: libs/powersync_repository
  shared:
    path: libs/shared

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
